<template><AppLayout><div class="space-y-4"><div class="flex items-center justify-between"><h1 class="page-title">{{ t('support.adminTitle') }}</h1><button class="btn btn-secondary" @click="load">{{ t('common.refresh') }}</button></div><div v-if="loading" class="card p-6 text-center">{{ t('common.loading') }}</div><div v-for="ticket in tickets" :key="ticket.id" class="card cursor-pointer p-4" @click="open(ticket.id)"><div class="flex justify-between"><span><span class="mr-2 rounded bg-gray-100 px-2 py-1 text-xs dark:bg-dark-700">{{ ticket.type === 'REFUND' ? t('support.refund') : t('support.suggestion') }}</span>{{ ticket.subject }}</span><span class="text-xs">{{ ticket.status }}</span></div><p class="mt-2 text-sm text-gray-500">{{ ticket.description }}</p><p class="mt-1 text-xs text-gray-400">#{{ ticket.id }} · {{ ticket.user_id }}</p></div></div><BaseDialog :show="!!selected" :title="selected?.ticket.subject || ''" width="wide" @close="selected = null"><div v-if="selected" class="space-y-4"><div v-for="message in selected.messages" :key="message.id" class="rounded-lg bg-gray-50 p-3 dark:bg-dark-800"><div class="text-xs text-gray-500">{{ message.sender_type }} · {{ new Date(message.created_at).toLocaleString() }}</div><p class="whitespace-pre-wrap text-sm">{{ message.body }}</p></div><textarea v-model="reply" class="input w-full" rows="3" /><div class="flex flex-wrap justify-end gap-2"><select v-model="status" class="input w-auto"><option value="OPEN">OPEN</option><option value="RESOLVED">RESOLVED</option><option value="CLOSED">CLOSED</option></select><button class="btn btn-secondary" @click="send">{{ t('support.reply') }}</button></div></div></BaseDialog></AppLayout></template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useI18n } from 'vue-i18n'; import AppLayout from '@/components/layout/AppLayout.vue'; import BaseDialog from '@/components/common/BaseDialog.vue'; import { supportTicketsAPI, type SupportTicket, type SupportTicketDetail, type SupportTicketStatus } from '@/api/supportTickets'; import { useAppStore } from '@/stores/app'; import { extractI18nErrorMessage } from '@/utils/apiError';
const { t } = useI18n(); const appStore = useAppStore(); const tickets=ref<SupportTicket[]>([]); const loading=ref(false); const selected=ref<SupportTicketDetail|null>(null); const reply=ref(''); const status=ref<SupportTicketStatus>('OPEN');
async function load(){loading.value=true;try{tickets.value=(await supportTicketsAPI.adminList()).data}catch(e){appStore.showError(extractI18nErrorMessage(e,t,'support.errors',t('common.error')))}finally{loading.value=false}}
async function open(id:number){try{selected.value=(await supportTicketsAPI.adminGet(id)).data;status.value=selected.value.ticket.status;reply.value=''}catch(e){appStore.showError(extractI18nErrorMessage(e,t,'support.errors',t('common.error')))}}
async function send(){if(!selected.value)return;try{if(reply.value.trim()){await supportTicketsAPI.adminAddMessage(selected.value.ticket.id,reply.value.trim())}await supportTicketsAPI.adminSetStatus(selected.value.ticket.id,status.value);selected.value=(await supportTicketsAPI.adminGet(selected.value.ticket.id)).data;reply.value='';await load()}catch(e){appStore.showError(extractI18nErrorMessage(e,t,'support.errors',t('common.error')))}}
onMounted(load)
</script>
