// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
)

// SupportTicketUpdate is the builder for updating SupportTicket entities.
type SupportTicketUpdate struct {
	config
	hooks    []Hook
	mutation *SupportTicketMutation
}

// Where appends a list predicates to the SupportTicketUpdate builder.
func (_u *SupportTicketUpdate) Where(ps ...predicate.SupportTicket) *SupportTicketUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SupportTicketUpdate) SetUserID(v int64) *SupportTicketUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableUserID(v *int64) *SupportTicketUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SupportTicketUpdate) AddUserID(v int64) *SupportTicketUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *SupportTicketUpdate) SetType(v string) *SupportTicketUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableType(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportTicketUpdate) SetStatus(v string) *SupportTicketUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableStatus(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *SupportTicketUpdate) SetSubject(v string) *SupportTicketUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableSubject(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SupportTicketUpdate) SetDescription(v string) *SupportTicketUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableDescription(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetContact sets the "contact" field.
func (_u *SupportTicketUpdate) SetContact(v string) *SupportTicketUpdate {
	_u.mutation.SetContact(v)
	return _u
}

// SetNillableContact sets the "contact" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableContact(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetContact(*v)
	}
	return _u
}

// ClearContact clears the value of the "contact" field.
func (_u *SupportTicketUpdate) ClearContact() *SupportTicketUpdate {
	_u.mutation.ClearContact()
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *SupportTicketUpdate) SetOrderID(v int64) *SupportTicketUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableOrderID(v *int64) *SupportTicketUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *SupportTicketUpdate) AddOrderID(v int64) *SupportTicketUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *SupportTicketUpdate) ClearOrderID() *SupportTicketUpdate {
	_u.mutation.ClearOrderID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketUpdate) SetUpdatedAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SupportTicketMutation object of the builder.
func (_u *SupportTicketUpdate) Mutation() *SupportTicketMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportTicketUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportTicketUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := supportticket.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := supportticket.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.subject": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportTicketUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticket.Table, supportticket.Columns, sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(supportticket.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(supportticket.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(supportticket.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportticket.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(supportticket.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(supportticket.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Contact(); ok {
		_spec.SetField(supportticket.FieldContact, field.TypeString, value)
	}
	if _u.mutation.ContactCleared() {
		_spec.ClearField(supportticket.FieldContact, field.TypeString)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(supportticket.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(supportticket.FieldOrderID, field.TypeInt64, value)
	}
	if _u.mutation.OrderIDCleared() {
		_spec.ClearField(supportticket.FieldOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticket.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportTicketUpdateOne is the builder for updating a single SupportTicket entity.
type SupportTicketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportTicketMutation
}

// SetUserID sets the "user_id" field.
func (_u *SupportTicketUpdateOne) SetUserID(v int64) *SupportTicketUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableUserID(v *int64) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SupportTicketUpdateOne) AddUserID(v int64) *SupportTicketUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *SupportTicketUpdateOne) SetType(v string) *SupportTicketUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableType(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportTicketUpdateOne) SetStatus(v string) *SupportTicketUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableStatus(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *SupportTicketUpdateOne) SetSubject(v string) *SupportTicketUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableSubject(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SupportTicketUpdateOne) SetDescription(v string) *SupportTicketUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableDescription(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetContact sets the "contact" field.
func (_u *SupportTicketUpdateOne) SetContact(v string) *SupportTicketUpdateOne {
	_u.mutation.SetContact(v)
	return _u
}

// SetNillableContact sets the "contact" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableContact(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetContact(*v)
	}
	return _u
}

// ClearContact clears the value of the "contact" field.
func (_u *SupportTicketUpdateOne) ClearContact() *SupportTicketUpdateOne {
	_u.mutation.ClearContact()
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *SupportTicketUpdateOne) SetOrderID(v int64) *SupportTicketUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableOrderID(v *int64) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *SupportTicketUpdateOne) AddOrderID(v int64) *SupportTicketUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *SupportTicketUpdateOne) ClearOrderID() *SupportTicketUpdateOne {
	_u.mutation.ClearOrderID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketUpdateOne) SetUpdatedAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SupportTicketMutation object of the builder.
func (_u *SupportTicketUpdateOne) Mutation() *SupportTicketMutation {
	return _u.mutation
}

// Where appends a list predicates to the SupportTicketUpdate builder.
func (_u *SupportTicketUpdateOne) Where(ps ...predicate.SupportTicket) *SupportTicketUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportTicketUpdateOne) Select(field string, fields ...string) *SupportTicketUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportTicket entity.
func (_u *SupportTicketUpdateOne) Save(ctx context.Context) (*SupportTicket, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketUpdateOne) SaveX(ctx context.Context) *SupportTicket {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportTicketUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := supportticket.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := supportticket.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.subject": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportTicketUpdateOne) sqlSave(ctx context.Context) (_node *SupportTicket, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticket.Table, supportticket.Columns, sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportTicket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportticket.FieldID)
		for _, f := range fields {
			if !supportticket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportticket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(supportticket.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(supportticket.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(supportticket.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportticket.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(supportticket.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(supportticket.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Contact(); ok {
		_spec.SetField(supportticket.FieldContact, field.TypeString, value)
	}
	if _u.mutation.ContactCleared() {
		_spec.ClearField(supportticket.FieldContact, field.TypeString)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(supportticket.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(supportticket.FieldOrderID, field.TypeInt64, value)
	}
	if _u.mutation.OrderIDCleared() {
		_spec.ClearField(supportticket.FieldOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticket.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SupportTicket{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
