// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportticketmessage"
)

// SupportTicketMessageUpdate is the builder for updating SupportTicketMessage entities.
type SupportTicketMessageUpdate struct {
	config
	hooks    []Hook
	mutation *SupportTicketMessageMutation
}

// Where appends a list predicates to the SupportTicketMessageUpdate builder.
func (_u *SupportTicketMessageUpdate) Where(ps ...predicate.SupportTicketMessage) *SupportTicketMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTicketID sets the "ticket_id" field.
func (_u *SupportTicketMessageUpdate) SetTicketID(v int64) *SupportTicketMessageUpdate {
	_u.mutation.ResetTicketID()
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *SupportTicketMessageUpdate) SetNillableTicketID(v *int64) *SupportTicketMessageUpdate {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// AddTicketID adds value to the "ticket_id" field.
func (_u *SupportTicketMessageUpdate) AddTicketID(v int64) *SupportTicketMessageUpdate {
	_u.mutation.AddTicketID(v)
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *SupportTicketMessageUpdate) SetSenderID(v int64) *SupportTicketMessageUpdate {
	_u.mutation.ResetSenderID()
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *SupportTicketMessageUpdate) SetNillableSenderID(v *int64) *SupportTicketMessageUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// AddSenderID adds value to the "sender_id" field.
func (_u *SupportTicketMessageUpdate) AddSenderID(v int64) *SupportTicketMessageUpdate {
	_u.mutation.AddSenderID(v)
	return _u
}

// SetSenderType sets the "sender_type" field.
func (_u *SupportTicketMessageUpdate) SetSenderType(v string) *SupportTicketMessageUpdate {
	_u.mutation.SetSenderType(v)
	return _u
}

// SetNillableSenderType sets the "sender_type" field if the given value is not nil.
func (_u *SupportTicketMessageUpdate) SetNillableSenderType(v *string) *SupportTicketMessageUpdate {
	if v != nil {
		_u.SetSenderType(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *SupportTicketMessageUpdate) SetBody(v string) *SupportTicketMessageUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *SupportTicketMessageUpdate) SetNillableBody(v *string) *SupportTicketMessageUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// Mutation returns the SupportTicketMessageMutation object of the builder.
func (_u *SupportTicketMessageUpdate) Mutation() *SupportTicketMessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportTicketMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportTicketMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketMessageUpdate) check() error {
	if v, ok := _u.mutation.SenderType(); ok {
		if err := supportticketmessage.SenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "sender_type", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.sender_type": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportTicketMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticketmessage.Table, supportticketmessage.Columns, sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TicketID(); ok {
		_spec.SetField(supportticketmessage.FieldTicketID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTicketID(); ok {
		_spec.AddField(supportticketmessage.FieldTicketID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(supportticketmessage.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSenderID(); ok {
		_spec.AddField(supportticketmessage.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SenderType(); ok {
		_spec.SetField(supportticketmessage.FieldSenderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(supportticketmessage.FieldBody, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticketmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportTicketMessageUpdateOne is the builder for updating a single SupportTicketMessage entity.
type SupportTicketMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportTicketMessageMutation
}

// SetTicketID sets the "ticket_id" field.
func (_u *SupportTicketMessageUpdateOne) SetTicketID(v int64) *SupportTicketMessageUpdateOne {
	_u.mutation.ResetTicketID()
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *SupportTicketMessageUpdateOne) SetNillableTicketID(v *int64) *SupportTicketMessageUpdateOne {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// AddTicketID adds value to the "ticket_id" field.
func (_u *SupportTicketMessageUpdateOne) AddTicketID(v int64) *SupportTicketMessageUpdateOne {
	_u.mutation.AddTicketID(v)
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *SupportTicketMessageUpdateOne) SetSenderID(v int64) *SupportTicketMessageUpdateOne {
	_u.mutation.ResetSenderID()
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *SupportTicketMessageUpdateOne) SetNillableSenderID(v *int64) *SupportTicketMessageUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// AddSenderID adds value to the "sender_id" field.
func (_u *SupportTicketMessageUpdateOne) AddSenderID(v int64) *SupportTicketMessageUpdateOne {
	_u.mutation.AddSenderID(v)
	return _u
}

// SetSenderType sets the "sender_type" field.
func (_u *SupportTicketMessageUpdateOne) SetSenderType(v string) *SupportTicketMessageUpdateOne {
	_u.mutation.SetSenderType(v)
	return _u
}

// SetNillableSenderType sets the "sender_type" field if the given value is not nil.
func (_u *SupportTicketMessageUpdateOne) SetNillableSenderType(v *string) *SupportTicketMessageUpdateOne {
	if v != nil {
		_u.SetSenderType(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *SupportTicketMessageUpdateOne) SetBody(v string) *SupportTicketMessageUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *SupportTicketMessageUpdateOne) SetNillableBody(v *string) *SupportTicketMessageUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// Mutation returns the SupportTicketMessageMutation object of the builder.
func (_u *SupportTicketMessageUpdateOne) Mutation() *SupportTicketMessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the SupportTicketMessageUpdate builder.
func (_u *SupportTicketMessageUpdateOne) Where(ps ...predicate.SupportTicketMessage) *SupportTicketMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportTicketMessageUpdateOne) Select(field string, fields ...string) *SupportTicketMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportTicketMessage entity.
func (_u *SupportTicketMessageUpdateOne) Save(ctx context.Context) (*SupportTicketMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketMessageUpdateOne) SaveX(ctx context.Context) *SupportTicketMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportTicketMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketMessageUpdateOne) check() error {
	if v, ok := _u.mutation.SenderType(); ok {
		if err := supportticketmessage.SenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "sender_type", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.sender_type": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportTicketMessageUpdateOne) sqlSave(ctx context.Context) (_node *SupportTicketMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticketmessage.Table, supportticketmessage.Columns, sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportTicketMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportticketmessage.FieldID)
		for _, f := range fields {
			if !supportticketmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportticketmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TicketID(); ok {
		_spec.SetField(supportticketmessage.FieldTicketID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTicketID(); ok {
		_spec.AddField(supportticketmessage.FieldTicketID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(supportticketmessage.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSenderID(); ok {
		_spec.AddField(supportticketmessage.FieldSenderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SenderType(); ok {
		_spec.SetField(supportticketmessage.FieldSenderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(supportticketmessage.FieldBody, field.TypeString, value)
	}
	_node = &SupportTicketMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticketmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
