// Code generated by ent, DO NOT EDIT.

package supportticketmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldID, id))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// SenderID applies equality check predicate on the "sender_id" field. It's identical to SenderIDEQ.
func SenderID(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldSenderID, v))
}

// SenderType applies equality check predicate on the "sender_type" field. It's identical to SenderTypeEQ.
func SenderType(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldSenderType, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldBody, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldTicketID, vs...))
}

// TicketIDGT applies the GT predicate on the "ticket_id" field.
func TicketIDGT(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldTicketID, v))
}

// TicketIDGTE applies the GTE predicate on the "ticket_id" field.
func TicketIDGTE(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldTicketID, v))
}

// TicketIDLT applies the LT predicate on the "ticket_id" field.
func TicketIDLT(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldTicketID, v))
}

// TicketIDLTE applies the LTE predicate on the "ticket_id" field.
func TicketIDLTE(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldTicketID, v))
}

// SenderIDEQ applies the EQ predicate on the "sender_id" field.
func SenderIDEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldSenderID, v))
}

// SenderIDNEQ applies the NEQ predicate on the "sender_id" field.
func SenderIDNEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldSenderID, v))
}

// SenderIDIn applies the In predicate on the "sender_id" field.
func SenderIDIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldSenderID, vs...))
}

// SenderIDNotIn applies the NotIn predicate on the "sender_id" field.
func SenderIDNotIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldSenderID, vs...))
}

// SenderIDGT applies the GT predicate on the "sender_id" field.
func SenderIDGT(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldSenderID, v))
}

// SenderIDGTE applies the GTE predicate on the "sender_id" field.
func SenderIDGTE(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldSenderID, v))
}

// SenderIDLT applies the LT predicate on the "sender_id" field.
func SenderIDLT(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldSenderID, v))
}

// SenderIDLTE applies the LTE predicate on the "sender_id" field.
func SenderIDLTE(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldSenderID, v))
}

// SenderTypeEQ applies the EQ predicate on the "sender_type" field.
func SenderTypeEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldSenderType, v))
}

// SenderTypeNEQ applies the NEQ predicate on the "sender_type" field.
func SenderTypeNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldSenderType, v))
}

// SenderTypeIn applies the In predicate on the "sender_type" field.
func SenderTypeIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldSenderType, vs...))
}

// SenderTypeNotIn applies the NotIn predicate on the "sender_type" field.
func SenderTypeNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldSenderType, vs...))
}

// SenderTypeGT applies the GT predicate on the "sender_type" field.
func SenderTypeGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldSenderType, v))
}

// SenderTypeGTE applies the GTE predicate on the "sender_type" field.
func SenderTypeGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldSenderType, v))
}

// SenderTypeLT applies the LT predicate on the "sender_type" field.
func SenderTypeLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldSenderType, v))
}

// SenderTypeLTE applies the LTE predicate on the "sender_type" field.
func SenderTypeLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldSenderType, v))
}

// SenderTypeContains applies the Contains predicate on the "sender_type" field.
func SenderTypeContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldSenderType, v))
}

// SenderTypeHasPrefix applies the HasPrefix predicate on the "sender_type" field.
func SenderTypeHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldSenderType, v))
}

// SenderTypeHasSuffix applies the HasSuffix predicate on the "sender_type" field.
func SenderTypeHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldSenderType, v))
}

// SenderTypeEqualFold applies the EqualFold predicate on the "sender_type" field.
func SenderTypeEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldSenderType, v))
}

// SenderTypeContainsFold applies the ContainsFold predicate on the "sender_type" field.
func SenderTypeContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldSenderType, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldBody, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.NotPredicates(p))
}
